name: Build

on:
  push:
    branches: [main]

jobs:
  build-test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Setting Node 16.14
        uses: actions/setup-node@v2
        with:
          node-version: "16.14"

      - name: Dependency Install
        run: npm i

      - name: Build
        run: npm run build
