name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.DOCS_GITHUB_TOKEN }}
            publish_dir: ./build
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com
